//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class MoveUp : ITool
	{
		public MoveUp ()
		{
		}

		public void Execute(ref ToolExecutionStatus status)
		{
			status.NextDirection = ToolOutputDirection.UP;
			status.Status = ToolStatus.NO_STATUS;
		}
		
		public bool CanUseImage()
		{
			return true;
		}
	}
}

