//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class ToolFactory
	{
		public static ITool GetTool(ToolTypes typeOfTool)
		{
			switch (typeOfTool) {
			case ToolTypes.MOVE_UP:
				return new MoveUp();
			case ToolTypes.MOVE_DOWN:
				return new MoveDown();
			case ToolTypes.MOVE_LEFT:
				return new MoveLeft();
			case ToolTypes.MOVE_RIGHT:
				return new MoveRight();
			case ToolTypes.DELETE:
				return new Delete();
			case ToolTypes.ACCEPT:
				return new Accept();
			case ToolTypes.REJECT:
				return new Reject();
			default:
				return null;
			}
		}
	}
}

