//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum ToolTypes
	{
		MOVE_UP,
		MOVE_DOWN,
		MOVE_LEFT,
		MOVE_RIGHT,
		DELETE,
		ACCEPT,
		REJECT,
		IF_CHECK
	}
	public enum ToolOutputDirection
	{
		NO_DIRECTION,
		UP,
		DOWN,
		LEFT,
		RIGHT
	}
	public enum ToolStatus
	{
		NO_STATUS,
		ACCEPTED,
		REJECTED,
		ERROR
	}
}

